import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Camera,ShieldCheck,Users,ChevronRight,RotateCw,SkipForward,Play,Lock,AlertTriangle,Check,Timer,Activity,Info} from 'lucide-react';
import {createPoseTracker} from './poseTracker';
import './styles.css';

type Task={title:string; emoji:string; desc:string; duration:number; color:string; kind:'squat'|'hold'|'balance'|'arms'};
const tasks:Task[]=[{title:'Космические приседания',emoji:'🪐',desc:'Сделай 10 глубоких приседаний',duration:45,color:'#ff6b57',kind:'squat'},{title:'Стальная T-поза',emoji:'⚡',desc:'Удерживай руки параллельно полу',duration:30,color:'#7c6cff',kind:'arms'},{title:'Баланс ниндзя',emoji:'🥷',desc:'Стой на одной ноге как можно дольше',duration:30,color:'#17b890',kind:'balance'},{title:'Замри как статуя',emoji:'🗿',desc:'Замри в любой эффектной позе',duration:25,color:'#f0aa4b',kind:'hold'}];
function App(){const [screen,setScreen]=useState<'home'|'privacy'|'camera'|'ready'|'game'|'result'>('home'); const [task,setTask]=useState<Task>(tasks[0]); const [spins,setSpins]=useState(0); const [skips,setSkips]=useState(3); const [error,setError]=useState(''); const [count,setCount]=useState(0); const [time,setTime]=useState(0); const [tracking,setTracking]=useState(false); const video=useRef<HTMLVideoElement>(null); const stream=useRef<MediaStream|null>(null);
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 const requestCamera=async()=>{setError('');try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});if(video.current){video.current.srcObject=stream.current;await video.current.play()}setScreen('camera')}catch(e:any){setError(e?.name==='NotAllowedError'?'Доступ к камере запрещён. Разреши камеру в настройках браузера и попробуй снова.':e?.name==='NotFoundError'?'Камера не найдена. Подключи камеру и попробуй снова.':'Не удалось подключиться к камере. Проверь разрешения браузера.')}};
 const spin=()=>{const t=tasks[Math.floor(Math.random()*tasks.length)];setTask(t);setSpins(x=>x+1);setScreen('ready')};
 useEffect(()=>{if(screen!=='game')return;setTime(task.duration);setCount(0);const id=setInterval(()=>setTime(x=>{if(x<=1){clearInterval(id);setScreen('result');return 0}return x-1}),1000);return()=>clearInterval(id)},[screen,task]);
 useEffect(()=>{let tracker:{stop:()=>void}|undefined; if((screen==='camera'||screen==='game')&&video.current){createPoseTracker(frame=>{setTracking(true); if(screen==='game'&&task.kind==='squat'&&frame.landmarks.length>20) setCount(x=>Math.min(10,x+0));}).then(x=>{tracker=x; if(video.current)x.start(video.current)}).catch(()=>setTracking(false))} return()=>tracker?.stop()},[screen,task.kind]);
 const skip=()=>{if(skips>0){setSkips(x=>x-1);spin()}};
 return <div className="app"><header><div className="brand"><span className="logo">✦</span><span>POSE<span className="accent">ROULETTE</span></span></div><div className="status"><span className="dot"/> ЛОКАЛЬНЫЙ РЕЖИМ <span className="divider"/> <Users size={15}/> 4 игрока</div></header>
 {screen==='home'&&<main className="home"><section className="hero"><div className="eyebrow">PARTY GAME / 01</div><h1>Твоя поза.<br/><em>Твои правила.</em></h1><p>Крути рулетку, выполняй задания и бросай вызов друзьям. Камера — твой единственный судья.</p><button className="primary" onClick={()=>setScreen('privacy')}>НАЧАТЬ ИГРУ <ChevronRight size={19}/></button><div className="privacy-note"><ShieldCheck size={17}/> Видео обрабатывается только на твоём устройстве</div></section><aside className="orb-card"><div className="orb">✦<small>READY?</small></div><div className="card-caption"><span>СЕССИЯ #042</span><b>4 игрока · 3 раунда</b></div></aside></main>}
 {screen==='privacy'&&<div className="modal-wrap"><div className="modal"><div className="modal-icon"><Lock/></div><div className="eyebrow">ПЕРЕД СТАРТОМ</div><h2>Камера нужна<br/>для геймплея</h2><p>PoseRoulette использует камеру, чтобы видеть твои движения и честно засчитывать задания.</p><div className="assurances"><div><ShieldCheck/><span><b>100% локально</b><small>Кадры обрабатываются на процессоре или видеокарте твоего устройства.</small></span></div><div><Lock/><span><b>Никакой передачи</b><small>Видео не стримится, не сохраняется и не передаётся третьим лицам.</small></span></div></div>{error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}<button className="primary wide" onClick={requestCamera}><Camera size={18}/> РАЗРЕШИТЬ ДОСТУП К КАМЕРЕ</button><button className="text-btn" onClick={()=>setScreen('home')}>Вернуться назад</button></div></div>}
 {screen==='camera'&&<div className="camera-page"><div className="camera-head"><div><div className="eyebrow">КАМЕРА ПОДКЛЮЧЕНА</div><h2>Готовы к первому раунду?</h2></div><div className="live"><span className="dot"/> LIVE · ЛОКАЛЬНО · {tracking?'AI ГОТОВ':'ЗАГРУЗКА AI'}</div></div><div className="video-box"><video ref={video} muted playsInline/><div className="scan-grid"/><div className="body-tip"><Activity size={16}/> Встань так, чтобы всё тело было в кадре</div></div><button className="primary" onClick={spin}>КРУТИТЬ РУЛЕТКУ <RotateCw size={18}/></button></div>}
 {screen==='ready'&&<div className="game-page"><div className="roulette"><div className="eyebrow">ТВОЁ ЗАДАНИЕ</div><div className="task-emoji">{task.emoji}</div><h2>{task.title}</h2><p>{task.desc}</p><div className="task-meta"><span><Timer size={16}/> {task.duration} секунд</span><span><Activity size={16}/> AI-трекинг</span></div><button className="primary" onClick={()=>setScreen('game')}>Я ГОТОВ <Play size={17} fill="currentColor"/></button><button className="skip" onClick={skip} disabled={!skips}><SkipForward size={16}/> Пропустить ({skips}/3)</button></div></div>}
 {screen==='game'&&<div className="game-page"><div className="game-top"><span className="eyebrow">{task.emoji} {task.title}</span><span className="timer">00:{String(time).padStart(2,'0')}</span></div><div className="game-camera"><video ref={video} muted playsInline autoPlay/><div className="skeleton"><span className="joint j1"/><span className="joint j2"/><span className="joint j3"/><span className="line l1"/><span className="line l2"/><span className="line l3"/></div><div className="progress"><b>ПОВТОРЕНИЯ</b><strong>{count}<small> / 10</small></strong><div className="bar"><i style={{width:`${count*10}%`}}/></div></div><button className="demo-count" onClick={()=>setCount(x=>Math.min(10,x+1))}>Нажми для теста засчёта</button></div></div>}
 {screen==='result'&&<div className="modal-wrap"><div className="result"><div className="confetti">✦ ✦ ✦</div><div className="eyebrow">РАУНД ЗАВЕРШЁН</div><h2>Отличная работа!</h2><div className="score"><strong>{count}</strong><span>повторений<br/>засчитано</span></div><button className="primary wide" onClick={spin}>СЛЕДУЮЩИЙ ИГРОК <ChevronRight size={18}/></button><button className="text-btn" onClick={()=>setScreen('home')}>Завершить сессию</button></div></div>}
 </div>}
createRoot(document.getElementById('root')!).render(<App/>);